=== Layne2002/LengMarcasDAM1/ExamenXMLKarimZinnatullin/Ejercicio3/Ejercicio3.XSD
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name='parking'>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TipoVehiculo" type="TipoVehiculo"/>
                            <xs:element name="matricula" type="matricula"/>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="socio" type="xs:boolean"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="matricula">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z]{3}[0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoVehiculo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="coche"/>
            <xs:enumeration value="moto"/>
            <xs:enumeration value="patinete"/>
            <xs:enumeration value="furgo"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Layne2002/LengMarcasDAM1/ExamenXMLKarimZinnatullin/Ejercicio3/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<parking xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio3.xsd">
  <vehiculo>
        <TipoVehiculo>coche</TipoVehiculo>
        <matricula>QEF4467</matricula>
        <nombre>Juan Cuesta</nombre>
        <socio>true</socio>
  </vehiculo>
  <vehiculo>
        <TipoVehiculo>patinete</TipoVehiculo>
        <matricula>KLO7387</matricula>
        <nombre>Mariv√≠ Bilbao</nombre>
        <socio>false</socio>
  </vehiculo>
</parking>
