=== Layne2002/LengMarcasDAM1/ExamenXMLKarimZinnatullin/Ejercicio1/Ejercicio1.dtd
<!ELEMENT elementos (elemento*)>
<!ELEMENT elemento (a, (b | c)*, d+, e?) >
<!ELEMENT a (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT c (#PCDATA)>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (#PCDATA)>

=== Layne2002/LengMarcasDAM1/ExamenXMLKarimZinnatullin/Ejercicio1/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE elementos SYSTEM "Ejercicio1.dtd">
<elementos>
    <elemento>
        <a>a</a>
        <b>b1</b>
        <b>b2</b>
        <d>d1</d>
        <e>e</e>
    </elemento>

    <elemento>
        <a>a</a>
        <d>d1</d>
        <d>d2</d>
    </elemento>

    <elemento>
        <a>a</a>
        <c>c1</c>
        <d>d1</d>
        <d>d2</d>
        <d>d3</d>
        <e>e</e>
    </elemento>

    <elemento>
        <a>a</a>
        <b>b1</b>
        <d>d1</d>

    </elemento>

    <elemento>
        <a>a</a>
        <c>c1</c>
        <d>d1</d>
        <d>d2</d>
        <d>d3</d>
        <e>e</e>
    </elemento>
</elementos>
